--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/benda95280/MyEntities
branches:
- master
projects:
  MyEntities:
    path: ""
    icon: "MyEntities.png"
    libs:
    - src: CortexPE/Commando/Commando
      version: ^0.4.0
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
...
