name: MyEntities
version: 0.1.2
main: Benda95280\MyEntities\MyEntities
api: ["3.11"]
authors:
  - Benda95280
  - XenialDan
extensions: ['gd']
permissions:
  MyEntities:
    description: Main permission
    default: op
    children:
      MyEntities.give:
        default: op
      MyEntities.head:
        default: op
      MyEntities.clone:
        default: op
      MyEntities.spawn:
        default: op
      MyEntities.attack:
        default: op
